---

services:
  redis:
    image: redis:7.4.2-alpine3.21
    container_name: redis
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3


  app1:
    build: .
    container_name: app1
    restart: always
    volumes:
      - ./certs:/app/certs:ro
    env_file:
      - .env
    depends_on:
      - redis


  app2:
    build: .
    container_name: app2
    restart: always
    volumes:
      - ./certs:/app/certs:ro
    env_file:
      - .env
    depends_on:
      - redis


  nginx:
    image: nginx:1.27.4-alpine3.21
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    depends_on:
      - app1
      - app2
    ports:
      - "8080:80"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
