---

services:
  app1:
    build: .
    container_name: app1
    volumes:
      - ./certs:/app/certs:ro
    env_file:
      - .env
    depends_on:
      - redis


  app2:
    build: .
    container_name: app2
    volumes:
      - ./certs:/app/certs:ro
    env_file:
      - .env
    depends_on:
      - redis


  redis:
    image: redis:7.4.2-alpine3.21
    container_name: redis


  nginx:
    image: nginx:1.27.4-alpine3.21
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    ports:
      - "8080:80"

